from __future__ import annotations

import copy
import hashlib
from datetime import datetime, timezone
from typing import Any

from contract_radar.inbox import build_daily_bid_inbox


ACTIVE_TASK_STATES = {"open", "waiting_on_user", "waiting_on_package", "ready_for_owner", "blocked"}

TASK_STATE_BY_INBOX_STATUS = {
    "ready_for_packet": "ready_for_owner",
    "resolve_gates": "waiting_on_user",
    "get_package": "waiting_on_package",
    "review_fit": "waiting_on_user",
    "watch": "open",
    "passed": "dismissed",
}

TASK_TYPE_BY_INBOX_STATUS = {
    "ready_for_packet": "owner_packet_approval",
    "resolve_gates": "resolve_compliance",
    "get_package": "acquire_official_package",
    "review_fit": "review_bid_fit",
    "watch": "monitor_opportunity",
    "passed": "pass_opportunity",
}


def run_daily_reconciliation(
    scan_result: dict[str, Any],
    analyses_by_opportunity: dict[str, dict[str, Any]] | None = None,
    *,
    previous_tasks: dict[str, dict[str, Any]] | None = None,
    opportunity_change_events: list[dict[str, Any]] | None = None,
    now: str = "",
) -> dict[str, Any]:
    """Build today's inbox and reconcile stable agent task state across runs."""
    timestamp = now or _utc_now()
    analyses = analyses_by_opportunity or {}
    inbox = build_daily_bid_inbox(scan_result, analyses, generated_at=timestamp)
    profile = scan_result.get("business_profile") if isinstance(scan_result.get("business_profile"), dict) else {}
    profile_id = str(profile.get("profile_id") or "")
    as_of = str(scan_result.get("as_of") or "")
    previous = _dict_of_dicts(previous_tasks)
    current_items = [item for item in inbox.get("items") or [] if isinstance(item, dict)]
    current_tasks = [_task_from_inbox_item(item, profile_id=profile_id, run_at=timestamp) for item in current_items]
    current_tasks = [task for task in current_tasks if task["task_state"] != "dismissed"]

    next_state = copy.deepcopy(previous)
    seen_task_ids: set[str] = set()
    active_opportunity_ids = {str(item.get("opportunity_id") or "") for item in current_items if item.get("opportunity_id")}
    new_task_ids: list[str] = []
    changed_task_ids: list[str] = []
    resolved_task_ids: list[str] = []
    deadline_alerts: list[dict[str, Any]] = []
    package_alerts: list[dict[str, Any]] = []
    addenda_alerts: list[dict[str, Any]] = []
    change_events = [dict(event) for event in opportunity_change_events or [] if isinstance(event, dict)]

    for task in current_tasks:
        task_id = task["task_id"]
        seen_task_ids.add(task_id)
        existing = previous.get(task_id)
        if not existing:
            task["first_seen_at"] = timestamp
            task["last_seen_at"] = timestamp
            task["last_changed_at"] = timestamp
            task["occurrence_count"] = 1
            task["change_reason"] = "New deterministic agent task."
            next_state[task_id] = task
            new_task_ids.append(task_id)
            continue

        updated = copy.deepcopy(existing)
        fingerprint = _task_fingerprint(task)
        previous_fingerprint = str(existing.get("fingerprint") or "")
        updated.update(task)
        updated["first_seen_at"] = str(existing.get("first_seen_at") or timestamp)
        updated["last_seen_at"] = timestamp
        updated["occurrence_count"] = int(existing.get("occurrence_count") or 0) + 1
        if previous_fingerprint and previous_fingerprint != fingerprint:
            updated["last_changed_at"] = timestamp
            updated["change_reason"] = _change_reason(existing, task)
            changed_task_ids.append(task_id)
            if str(existing.get("submission_deadline") or "") != str(task.get("submission_deadline") or ""):
                deadline_alerts.append(_deadline_alert(existing, task))
            if _package_status_changed(existing, task):
                package_alerts.append(_package_alert(existing, task))
        else:
            updated["last_changed_at"] = str(existing.get("last_changed_at") or timestamp)
            updated["change_reason"] = ""
        next_state[task_id] = updated

    for task_id, existing in previous.items():
        if task_id in seen_task_ids:
            continue
        opportunity_id = str(existing.get("opportunity_id") or "")
        if opportunity_id not in active_opportunity_ids:
            continue
        if str(existing.get("task_state") or "") not in ACTIVE_TASK_STATES:
            continue
        completed = copy.deepcopy(existing)
        completed["task_state"] = "done"
        completed["last_seen_at"] = timestamp
        completed["last_changed_at"] = timestamp
        completed["change_reason"] = "No longer generated by current deterministic agent state."
        next_state[task_id] = completed
        resolved_task_ids.append(task_id)

    deadline_alerts.extend(_change_event_alerts(change_events, "deadline_changed"))
    package_alerts.extend(_change_event_alerts(change_events, "package_available"))
    addenda_alerts.extend(_change_event_alerts(change_events, "addendum_detected"))

    run = {
        "run_id": _id("daily-run", profile_id, as_of, timestamp),
        "started_at": timestamp,
        "finished_at": timestamp,
        "profile_id": profile_id,
        "as_of": as_of,
        "opportunities_checked": len(_opportunity_ids(scan_result)),
        "new_tasks": new_task_ids,
        "changed_tasks": changed_task_ids,
        "resolved_tasks": resolved_task_ids,
        "deadline_alerts": deadline_alerts,
        "package_alerts": package_alerts,
        "addenda_alerts": addenda_alerts,
        "change_events": change_events,
        "errors": [],
    }
    inbox["run_summary"] = {
        "run_id": run["run_id"],
        "new": len(new_task_ids),
        "changed": len(changed_task_ids),
        "resolved": len(resolved_task_ids),
        "deadline_alerts": len(deadline_alerts),
        "package_alerts": len(package_alerts),
        "addenda_alerts": len(addenda_alerts),
        "change_events": len(change_events),
    }
    inbox["items"] = [_with_reconciled_fields(item, next_state, profile_id=profile_id) for item in current_items]
    return {
        "daily_inbox": inbox,
        "daily_run": run,
        "agent_task_state": next_state,
        "current_agent_tasks": [next_state[task["task_id"]] for task in current_tasks if task["task_id"] in next_state],
    }


def _task_from_inbox_item(item: dict[str, Any], *, profile_id: str, run_at: str) -> dict[str, Any]:
    status = str(item.get("status") or "review_fit")
    opportunity_id = str(item.get("opportunity_id") or "")
    task_type = str(item.get("task_type") or TASK_TYPE_BY_INBOX_STATUS.get(status, "review_bid_fit"))
    task_state = TASK_STATE_BY_INBOX_STATUS.get(status, "waiting_on_user")
    task = {
        "task_id": _stable_task_id(profile_id, item, task_type),
        "profile_id": profile_id,
        "opportunity_id": opportunity_id,
        "analysis_id": str(item.get("analysis_id") or ""),
        "task_type": task_type,
        "task_state": task_state,
        "inbox_status": status,
        "title": str(item.get("next_action") or item.get("status_label") or "Review bid task"),
        "blocker": str(item.get("blocker") or ""),
        "decision_label": str(item.get("decision_label") or ""),
        "source_task_id": str(item.get("source_task_id") or ""),
        "source_gate_id": str(item.get("source_gate_id") or ""),
        "source_requirement_id": str(item.get("source_requirement_id") or ""),
        "acquisition_status": str(item.get("acquisition_status") or ""),
        "bid_state": str(item.get("bid_state") or ""),
        "submission_deadline": str(item.get("submission_deadline") or ""),
        "days_until_deadline": item.get("days_until_deadline"),
        "recommended_bid": float(item.get("recommended_bid") or 0),
        "fingerprint": "",
        "created_from": "daily_bid_inbox",
        "updated_at": run_at,
    }
    task["fingerprint"] = _task_fingerprint(task)
    return task


def _stable_task_id(profile_id: str, item: dict[str, Any], task_type: str) -> str:
    source_id = (
        str(item.get("source_task_id") or "").strip()
        or str(item.get("source_gate_id") or "").strip()
        or str(item.get("source_requirement_id") or "").strip()
        or str(item.get("status") or "").strip()
    )
    return _id("agent-task", profile_id, item.get("opportunity_id"), task_type, source_id)


def _task_fingerprint(task: dict[str, Any]) -> str:
    fields = {
        "analysis_id": str(task.get("analysis_id") or ""),
        "task_state": str(task.get("task_state") or ""),
        "inbox_status": str(task.get("inbox_status") or ""),
        "title": str(task.get("title") or ""),
        "blocker": str(task.get("blocker") or ""),
        "acquisition_status": str(task.get("acquisition_status") or ""),
        "bid_state": str(task.get("bid_state") or ""),
        "submission_deadline": str(task.get("submission_deadline") or ""),
        "days_until_deadline": str(task.get("days_until_deadline") or ""),
    }
    return _id("fingerprint", fields)


def _change_reason(existing: dict[str, Any], task: dict[str, Any]) -> str:
    if str(existing.get("submission_deadline") or "") != str(task.get("submission_deadline") or ""):
        return "Submission deadline changed."
    if str(existing.get("task_state") or "") != str(task.get("task_state") or ""):
        return "Task state changed."
    if str(existing.get("acquisition_status") or "") != str(task.get("acquisition_status") or ""):
        return "Official package acquisition status changed."
    if str(existing.get("bid_state") or "") != str(task.get("bid_state") or ""):
        return "Bid state changed."
    return "Task details changed."


def _deadline_alert(existing: dict[str, Any], task: dict[str, Any]) -> dict[str, Any]:
    return {
        "task_id": str(task.get("task_id") or ""),
        "opportunity_id": str(task.get("opportunity_id") or ""),
        "old_deadline": str(existing.get("submission_deadline") or ""),
        "new_deadline": str(task.get("submission_deadline") or ""),
    }


def _package_status_changed(existing: dict[str, Any], task: dict[str, Any]) -> bool:
    old_status = str(existing.get("acquisition_status") or "")
    new_status = str(task.get("acquisition_status") or "")
    return bool(old_status and old_status != new_status)


def _package_alert(existing: dict[str, Any], task: dict[str, Any]) -> dict[str, Any]:
    return {
        "task_id": str(task.get("task_id") or ""),
        "opportunity_id": str(task.get("opportunity_id") or ""),
        "old_status": str(existing.get("acquisition_status") or ""),
        "new_status": str(task.get("acquisition_status") or ""),
    }


def _change_event_alerts(events: list[dict[str, Any]], event_type: str) -> list[dict[str, Any]]:
    alerts = []
    for event in events:
        if str(event.get("event_type") or "") != event_type:
            continue
        alerts.append(
            {
                "event_id": str(event.get("event_id") or ""),
                "opportunity_id": str(event.get("opportunity_id") or ""),
                "reason": str(event.get("reason") or ""),
                "old_value": str(event.get("old_value") or ""),
                "new_value": str(event.get("new_value") or ""),
                "detected_at": str(event.get("detected_at") or ""),
            }
        )
    return alerts


def _with_reconciled_fields(
    item: dict[str, Any],
    task_state: dict[str, dict[str, Any]],
    *,
    profile_id: str,
) -> dict[str, Any]:
    task_type = str(item.get("task_type") or TASK_TYPE_BY_INBOX_STATUS.get(str(item.get("status") or ""), "review_bid_fit"))
    task_id = _stable_task_id(profile_id, item, task_type)
    matched = task_state.get(task_id)
    for candidate in task_state.values():
        if matched:
            break
        if (
            str(candidate.get("opportunity_id") or "") == str(item.get("opportunity_id") or "")
            and str(candidate.get("task_type") or "") == task_type
            and str(candidate.get("inbox_status") or "") == str(item.get("status") or "")
            and str(candidate.get("task_state") or "") != "done"
        ):
            matched = candidate
            break
    enriched = dict(item)
    if matched:
        enriched["agent_task_id"] = str(matched.get("task_id") or task_id)
        enriched["task_state"] = str(matched.get("task_state") or "")
        enriched["first_seen_at"] = str(matched.get("first_seen_at") or "")
        enriched["last_changed_at"] = str(matched.get("last_changed_at") or "")
        enriched["occurrence_count"] = int(matched.get("occurrence_count") or 0)
        enriched["change_reason"] = str(matched.get("change_reason") or "")
    return enriched


def _opportunity_ids(scan_result: dict[str, Any]) -> set[str]:
    ids: set[str] = set()
    for bucket in ("top_opportunities", "watchlist", "all_evaluated", "skipped"):
        for item in scan_result.get(bucket) or []:
            if not isinstance(item, dict):
                continue
            solicitation = item.get("solicitation") if isinstance(item.get("solicitation"), dict) else {}
            opportunity_id = str(solicitation.get("document_number") or item.get("opportunity_id") or "").strip()
            if opportunity_id:
                ids.add(opportunity_id)
    return ids


def _dict_of_dicts(value: Any) -> dict[str, dict[str, Any]]:
    if not isinstance(value, dict):
        return {}
    return {
        str(key): copy.deepcopy(item)
        for key, item in value.items()
        if str(key).strip() and isinstance(item, dict)
    }


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _id(prefix: str, *parts: Any) -> str:
    digest = hashlib.sha256(repr(parts).encode("utf-8")).hexdigest()[:16]
    return f"{prefix}-{digest}"
